[package]
name = "seahorse"
description = "A generic AAP-style cryptocurrency wallet."
authors = ["Jeb Bearer <jeb.bearer@translucence.net>"]
version = "0.1.0"
edition = "2018"

[dependencies]
arbitrary = { version="1.0", features=["derive"] }
arbitrary-wrappers = { git = "ssh://git@github.com/SpectrumXYZ/arbitrary-wrappers.git" }
ark-serialize = { version = "0.3.0", features = ["derive"] }
ark-std = { version = "0.3.0", default-features = false }
async-scoped = { version = "0.7.0", features = ["use-async-std"] }
async-std = { version = "1.10.0", features = ["unstable", "attributes"] }
async-trait = "0.1.51"
atomic_store = { git = "ssh://git@github.com/SpectrumXYZ/atomicstore.git" }
bincode = "1.3.3"
chacha20 = "0.8.1"
chrono = "0.4.19"
commit = { git = "ssh://git@github.com/SpectrumXYZ/commit.git", rev = "f48cd52c59755eade0605111826eef3df6abdcf8" }
futures = "0.3.16"
generic-array = { version = "0.14.4", features = ["serde"] }
hmac = "0.11.0"
itertools = "0.10.1"
jf-aap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "eca7b7e85718c7770c24ad90dd34b8a07209a01b"}
jf-utils = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish.git" }
key-set = { git = "ssh://git@github.com/SpectrumXYZ/key-set.git" }
lazy_static = "1.4.0"
mnemonic = "1.0.1"
net = { git = "ssh://git@github.com/SpectrumXYZ/net.git", rev = "8d04d5578de00539bbaa218eaa1c12d02adef3ba" }
proptest = { version = "0.8.7", optional = true }
rand_chacha = { version = "0.3.1", features = ["serde1"] }
reef = { git = "ssh://git@github.com/SpectrumXYZ/reef.git", rev = "6e3e7f683d2f8c1c1da662301f8ca8c2863018cc" }
rpassword = "5.0.1"
rust-argon2 = "0.8.3"
rustyline = "9.0.0"
serde = { version = "1.0", features = ["derive"] }
sha3 = "^0.9"
snafu = { version = "0.6.10", features = ["backtraces"] }
strum = "0.20"
strum_macros = "0.20.1"
surf = "2.3.1"
tagged-base64 = { git = "ssh://git@github.com/SpectrumXYZ/tagged-base64.git", branch = "main"}
tempdir = "0.3.7"
universal-param = { git = "ssh://git@github.com/SpectrumXYZ/universal-param.git" }
zeroize = "1.3"
zerok-macros = { git = "ssh://git@github.com/SpectrumXYZ/zerok-macros.git" }

[dev-dependencies]
proptest = "0.8.7"

[features]
testing = ["proptest"]
