name: Benchmarks

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

env:
  RUSTFLAGS: -Ctarget-cpu=native

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        name: Cancel Outdated Builds
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: "1.56"
          override: true
          default: true
          components: rustfmt, clippy

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v1

      - name: Bench
        run: cargo bench --features=testing
