name: Benchmarks

on:
  push:
    branches:
      - main
      - release-*
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  RUSTFLAGS: -Ctarget-cpu=native

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        name: Cancel Outdated Builds
        with:
          access_token: ${{ github.token }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.63

      - uses: actions/checkout@v3.2.0
        name: Checkout Repository

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2

      - name: Bench
        run: cargo bench --features=testing
