name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: registry.gitlab.com/asuran-rs/containers/rust-sccache-docker:1.56
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v1

      - name: Format Check
        run: cargo fmt -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ github.token }}
          args: --workspace --all-targets --all-features -- -D warnings

      - name: Audit
        run: cargo audit --ignore RUSTSEC-2020-0159 --ignore RUSTSEC-2020-0071

      - name: Build Tests
        run: |
          cargo test --workspace --release --no-run

      - name: Build Benchmarks
        run: |
          cargo bench --features=testing --no-run

      - name: Build Slow Tests
        # Make sure the slow tests build, but don't run them (we have another workflow for that).
        run: cargo test --release --features=slow-tests --no-run

      - name: Test
        run: |
          cargo test --workspace --release --verbose -- -Zunstable-options --report-time --test-threads 2
        timeout-minutes: 30

      - name: Generate Documentation
        run: |
          cargo doc --no-deps --lib --release
          cp -R target/doc public
          echo '<meta http-equiv="refresh" content="0; url=seahorse">' > public/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: seahorse.docs.espressosys.com
