name: Code Coverage

on:
  push:
    branches:
      - main
      - coverage
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.63

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Generate code coverage
        run: |
          mkdir coverage
          SEAHORSE_TEST_TXN_HISTORY_TIME_TOLERANCE=10 cargo llvm-cov --lib --bins --tests --release --workspace --all-features --lcov --output-path ./coverage/lcov.info
        timeout-minutes: 240

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
