name: Code Coverage Workflow

on:
  schedule:
    - cron: '0 1 * * 0'
  pull_request: # Will disable this once I see the workflow working correctly
  workflow_dispatch:

jobs:
  code-coverage:
    runs-on: [self-hosted, X64]
    container:
      image: ghcr.io/espressosystems/nix:2.8.1
      volumes:
        - github_nix_281:/nix
    timeout-minutes: 240
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: cachix/cachix-action@v10
        with:
          name: espresso-systems-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Generate coverage reports
        run: |
          git config --global --add safe.directory "$PWD"
          nix run "github:NixOS/nix?ref=1849e6a1f64734c488c2b1469249d65ce08cef93" -- develop .#perfShell -c env SEAHORSE_TEST_TXN_HISTORY_TIME_TOLERANCE=10 cargo-llvm-cov llvm-cov --lib --bins --tests --release --workspace --all-features --lcov --output-path lcov.info -- --test-threads=1

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
          fail_ci_if_error: true
