name: Slow Tests

on:
  push:
    branches:
      - main
      - release-*
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  RUST_TEST_THREADS: 4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        name: Cancel Outdated Builds
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3.3.0
        name: Checkout Repository

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.63

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Run Tests
        run: cargo test --release --features=slow-tests
